### ISSUE TITLE
Supporting custom hash functions

### ISSUE THREAD

**Issue by codesoap** [FiloSottile/edwards25519#14]
I'm not very familiar with how ed25519 works, so please correct me if I'm wrong. To me it seems like a hash function (usually SHA-512) is somehow involved with the calculations on the curve. I'm currently toying with the Nano crypto-currency and it apparently uses the `blake2b` hash when working with ed25519: https://docs.nano.org/integration-guides/the-basics/#account-public-key

Would it be possible to add support for custom hash functions to this library? Would you find this desirable?

**Comment by FiloSottile** [comment]
SHA-512 is involved in the Ed25519 signature scheme, not in the edwards25519 curve calculations.

This library implements only the latter, so it gives you the components to build whatever Ed25519 variant you like.

Indeed, the library does not import any hash function! https://pkg.go.dev/filippo.io/edwards25519?tab=imports

**Comment by codesoap** [comment]
Thanks for educating me! I'll read some more about Ed25519 signatures.
