### ISSUE TITLE
avo doesn't know that `BP` is callee-saved

### ISSUE THREAD

**Issue by Yawning** [FiloSottile/edwards25519#16]
The avo-generated assembly is using `BP` as a general purpose register without saving/restoring it, which isn't allowed.  Since you've ran into this once before, I assume it's just an oversight.

At least it's easy enough to fix since there is 1 gp register free.

**Comment by FiloSottile** [comment]
Yeah, this is a known issue in avo: mmcloughlin/avo#156

For [the upstream CL](https://go-review.googlesource.com/c/go/+/276272) I manually patched the generated assembly to make the TryBots happy, but I hear @mmcloughlin is working on a fix in avo, so if that comes soon enough I might just wait for that here.

**Comment by Yawning** [comment]
Could manually save/restore the register as a workaround.  If you don't want to be at the whims of avo's register allocator, or add a stack frame, just use an XMM register.

**Comment by mmcloughlin** [comment]
Yes, working on it. I'm intending to solve it with two changes:

1. Pass that runs after register allocation that checks whether `BP` has been used and forces a non-zero frame size (if it's not already).
2. De-prioritize `BP` in the register allocator, so it's only used if there is high register pressure.

The first of these is easy. The second is a little more delicate: at the moment the register allocator doesn't have any concept of priority so I'm trying to come up with the cleanest way of implementing it.

If you have thoughts I'd welcome comments on mmcloughlin/avo#156.

**Comment by mmcloughlin** [comment]
The frame pointer issue mmcloughlin/avo#156 should be fixed in latest version of `avo`, tagged `v0.2.0`.

**Comment by FiloSottile** [comment]
Awesome, thank you! Updated and regenerated :)
