### ISSUE TITLE
Add Element.SetBytesWide (or similar)

### ISSUE THREAD

**Issue by Yawning** [FiloSottile/edwards25519#17]
While this partially falls under "Why aren't you using Ristretto"[0], implementing the IETF CFRG hash-to-curve draft's Curve25519/Ed25519 suites requires being able to derive a field element by reducing a 384-bit integer.

The problematic part is "5.3. hash_to_field implementation" which specifies thus:
```
   - L = ceil((ceil(log2(p)) + k) / 8), where k is the security
     parameter of the suite (e.g., k = 128).

[snip]

   6.     tv = substr(uniform_bytes, elm_offset, L)
   7.     e_j = OS2IP(tv) mod p
```

As far as I'm concerned the input being wider than L is fine, as is the input being little-endian (for consistency with everything else).

[0]: Why the method for deriving the required field elements is different between ristretto255 and curve25519/ed25519 in the relevant specification puzzles me, but it's not my draft.

**Comment by FiloSottile** [comment]
If I understand correctly, they are just trying to uniformly sample a field element at random. Curve25519 is nice in that the probability of introducing bias by just reducing 255 random bits is 19 / 2^255, less than 2^-250, so negligible.

What they are doing looks like a fully general method to sample without bias for any modulo. It’s unfortunate that in the name of generality they are introducing complexity for curves that had designed it away.

Concretely, it’s not trivial to implement, as we currently don’t have a general wide reduction for the base field. We can probably crib one from the multiplication function, though. I’ll look into it.

I wonder if they realize they are requiring operations that are unlikely to be already available in existing libraries, causing new code and APIs to be introduced, or more likely leading implementers to use non-constant time alternatives.

**Comment by Yawning** [comment]
> Concretely, it’s not trivial to implement, as we currently don’t have a general wide reduction for the base field. We can probably crib one from the multiplication function, though. I’ll look into it.

I'm fairly sure you can implement this like how libsodum does it (`fe25519_reduce64`).

> I wonder if they realize they are requiring operations that are unlikely to be already available in existing libraries, causing new code and APIs to be introduced, or more likely leading implementers to use non-constant time alternatives.

They made concessions for ristretto255, and section 5.2 discusses alternative implementations, but yeah.  Kind of weird that they don't just provide the alternative, because the only reason why a wide reduction is needed is to implement this draft...

**Comment by FiloSottile** [comment]
Is it me or the libsodium implementation ignores the top bit? Maybe for consistency with the regular decoding function?

**Comment by Yawning** [comment]
Indeed it does.  Since the function is internal, my guess is because it's only ever used to implement `hash_to_field` which takes 384-bits of actual input, zero extended..

For a more general purpose library, I would do one of, just document that the MSB is ignored (which seems kind of suboptimal long term), actually honor the MSB, or make the routine take a 384-bit (48-byte) slice and zero-extend internally.

**Comment by FiloSottile** [comment]
Dropped an implementation in #18. Mind giving it a spin? I'll email the CFRG list about maybe not requiring a new field op.

**Comment by Yawning** [comment]
> Dropped an implementation in #18. Mind giving it a spin? I'll email the CFRG list about maybe not requiring a new field op.

Sure.  I need to extract my h2c implementation and switch the underlying library to yours so it'll take a bit.  Sorry (and thanks for the fast response).

At a cursory glance it looks correct.
