### ISSUE TITLE
field/Element.SqrtRatio is not alias-safe

### ISSUE THREAD

**Issue by Yawning** [FiloSottile/edwards25519#19]
If `r` aliases either `u` or `v` (eg: `_, isSquare := foo.SqrtRatio(one, &foo)`), output is not what is expected, because `r.Multiply(uv3, r.Pow22523(uv7))` happens before the final uses of `u` or `v`.

**Comment by FiloSottile** [comment]
Thank you! We even have comprehensive tests for aliasing, but SqrtRatio wasn't wired into them.
