### ISSUE TITLE
VarTimeDoubleScalarMult is missing an argument

### ISSUE THREAD

**Issue by wbl** [FiloSottile/edwards25519#2]
The documentation says VarTimeDoubleScalarBaseMult sets v = a * A + b * B, and returns v. 

The function's signature is `func (v *Point) VarTimeDoubleScalarBaseMult(a *Scalar, A *Point, b *Scalar) *Point`

What is B?

**Comment by FiloSottile** [comment]
B is the basepoint (hence `Base` in the name), I'll clarify the docs, thank you! This API is for Ed25519 verification.
