### ISSUE TITLE
Error building with old versions of Go 1.10

### ISSUE THREAD

**Issue by mappu** [FiloSottile/edwards25519#26]
The build fails on Go1.10 because of dependencies on the math/bits library:

```
# vendor/golang.org/x/crypto/curve25519/internal/field
..\vendor\golang.org\x\crypto\curve25519\internal\field\fe.go:328:12: undefined: bits.Mul64
..\vendor\golang.org\x\crypto\curve25519\internal\field\fe_generic.go:17:12: undefined: bits.Mul64
..\vendor\golang.org\x\crypto\curve25519\internal\field\fe_generic.go:23:12: undefined: bits.Mul64
..\vendor\golang.org\x\crypto\curve25519\internal\field\fe_generic.go:24:11: undefined: bits.Add64
..\vendor\golang.org\x\crypto\curve25519\internal\field\fe_generic.go:25:10: undefined: bits.Add64
```

These functions were added in Go 1.12 according to https://pkg.go.dev/math/bits#Add64 .

I am building my app under Go1.10 (as well as also under modern versions) to keep running on some old versions of Windows that go tip does not support.

Is it feasible to add a `_go110.go` file here? Or is this just the end of the line for old versions of Go?

**Comment by FiloSottile** [comment]
Go 1.10 has been out of security support for almost three years. We don't support anything out of security support, sorry.
